---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    # - nephelaiio.tree
    # - andrewrothstein.tmux
    # - manala.vim
    - geerlingguy.git
    - telusdigital.fish
    - gantsign.visual-studio-code
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: vagrant
          visual_studio_code_extensions:
            - Shan.code-settings-sync
    - wtanaka.chrome
    - geerlingguy.dotfiles
    - Stouts.timezone
    # - azavea.unzip
    #heroku-toolbelt throws error in biit-mac, no idea why. TO-DO: we can install it in post_bash_script
    # - pablocrivella.heroku-toolbelt