---
- src: kbrebanov.git
- src: geerlingguy.dotfiles
- src: nephelaiio.tree
- src: andrewrothstein.tmux
- src: manala.vim
- src: gantsign.visual-studio-code
- src: gantsign.visual-studio-code-extensions
- src: telusdigital.fish
- src: Stouts.timezone